apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k6-deployment
  labels:
    app: k6
spec:
  replicas: 0
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
      - name: utilities
        image: quay.io/sudermanjr/utilities:latest
        command: [ "/bin/bash", "/utilities/utility-run.sh" ]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        volumeMounts:
        - name: output
          mountPath: /output
        - name: utilities
          mountPath: /utilities
      - name: k6
        image: loadimpact/k6:0.22.1
        command: ["ash", "/k6/run.sh"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        volumeMounts:
        - name: k6files
          mountPath: /k6
        - name: output
          mountPath: /output
      volumes:
        - name: k6files
          configMap:
            name: k6files
        - name: utilities
          configMap:
            name: utilities
        - name: output
          emptyDir: {}
